# Generated by Django 5.2.1 on 2025-05-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_joiner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
